### ISSUE TITLE
[dist] allow FQDN for server/scheduler nodes in the config files 

### ISSUE THREAD

**Issue by drahnr** [paritytech/cachepot#79]
Currently only IP addresses are accepted, but we really should accept FQDN for use with kubernetes or nomad or service meshes in general.

**Comment by gww-parity** [comment]
https://en.wikipedia.org/wiki/Fully_qualified_domain_name

**Comment by Xanewok** [comment]
@gww-parity I recall you wanted to take it on. Is there a feature branch that you were working on or is the issue still up for grabs?

**Comment by gww-parity** [comment]
please take it.

**Comment by Xanewok** [comment]
IIRC we authenticate build servers via IP and issue certificates bound to that IP. Will this change the way we issue certificates (IP can change for the DNS record in the meantime) or do we intend to treat that mostly as a help to let the DNS initially resolve an IP (and stick to it) rather than resolving and hard-coding it ourselves?
